document.addEventListener('DOMContentLoaded',()=>{
 const $=(s,p=document)=>p.querySelector(s), $$=(s,p=document)=>[...p.querySelectorAll(s)];
 const initiated=/iniciada\.html$/i.test(location.pathname)||/perfil\.html$/i.test(location.pathname)||/carrito\.html$/i.test(location.pathname)||/metodosdepago\.html$/i.test(location.pathname);
 const publicPage=!initiated;
 const cartKey='pixelStoreCart';
 const getCart=()=>{try{return JSON.parse(localStorage.getItem(cartKey))||[]}catch{return[]}};
 const saveCart=c=>{localStorage.setItem(cartKey,JSON.stringify(c));updateCartCount()};
 function updateCartCount(){let n=getCart().reduce((a,x)=>a+(x.qty||1),0);$$('[data-cart-count]').forEach(e=>e.textContent=n)} updateCartCount();
 // Plataforma dropdown
 $$('.category-trigger').forEach(b=>b.addEventListener('click',e=>{e.stopPropagation();b.closest('.category-dropdown')?.classList.toggle('open')}));
 document.addEventListener('click',e=>$$('.category-dropdown.open').forEach(x=>{if(!x.contains(e.target))x.classList.remove('open')}));
 // Public cart always requires login
 $$('a.cart-link, a[href="carrito.html"], a[href="carritoiniciada.html"]').forEach(a=>{a.addEventListener('click',async e=>{if(!initiated){e.preventDefault();location.href='iniciar.html?return=carrito.html'}})});
 // Search
 const params=new URLSearchParams(location.search),initialQ=params.get('q')||'';
 $$('[data-search]').forEach(input=>{input.value=initialQ;const apply=()=>{let q=input.value.trim().toLowerCase(),cards=$$('.game-card');if(!cards.length){location.href=(initiated?'explorariniciada.html':'explorar.html')+(q?'?q='+encodeURIComponent(q):'');return}let n=0;cards.forEach(c=>{let ok=!q||(c.dataset.game||'').includes(q);c.style.display=ok?'':'none';if(ok)n++});$('#emptySearch')?.style.setProperty('display',n?'none':'block')};input.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();apply()}});input.addEventListener('input',()=>{$$('.game-card').length&&apply()})});
 // Filters/sorting
 $$('.filter-btn').forEach(btn=>btn.addEventListener('click',()=>{$$('.filter-btn').forEach(b=>b.classList.remove('active'));btn.classList.add('active');let f=btn.dataset.filter,n=0;$$('.catalog-grid .game-card').forEach(c=>{let p=c.dataset.platform||'',ok=f==='all'||(f==='ps5'&&p.includes('ps5'))||(f==='xbox'&&p.includes('xbox'))||(f==='switch'&&p.includes('switch'));c.style.display=ok?'':'none';if(ok)n++});$('#emptySearch')?.style.setProperty('display',n?'none':'block')}));
 const sort=$('#sortGames'),grid=$('#catalogGrid');if(sort&&grid)sort.addEventListener('change',()=>{$$('.game-card',grid).sort((a,b)=>{let v=sort.value;if(v==='name')return a.querySelector('h3').textContent.localeCompare(b.querySelector('h3').textContent);let p=x=>parseInt((x.querySelector('strong')?.textContent||'').replace(/\D/g,''))||0;return v==='price-low'?p(a)-p(b):v==='price-high'?p(b)-p(a):0}).forEach(c=>grid.appendChild(c))});
 // Login/register with server accounts
 async function post(url,data){let r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}),j=await r.json().catch(()=>({message:'Error del servidor.'}));return{r,j}}
 $('#loginForm')?.addEventListener('submit',async e=>{e.preventDefault();let m=$('#loginMessage'),{r,j}=await post('/api/login',{email:$('#loginEmail').value,password:$('#loginPassword').value});m.textContent=j.message||'';if(r.ok){let ret=new URLSearchParams(location.search).get('return');location.href=ret||'indexiniciada.html'}});
 $('#registerForm')?.addEventListener('submit',async e=>{e.preventDefault();let m=$('#registerMessage'),pw=$('#registerPassword').value;if(pw!==$('#registerConfirm').value){m.textContent='Las contraseñas no coinciden.';return}let{r,j}=await post('/api/register',{name:$('#registerName').value,username:$('#registerUsername').value,email:$('#registerEmail').value,password:pw});m.textContent=j.message||'';if(r.ok)location.href='indexiniciada.html'});
 $('#logoutBtn')?.addEventListener('click',async()=>{await post('/api/logout',{});location.href='index.html'});
 // Protect initiated pages in browser too
 if(initiated&&!location.pathname.endsWith('iniciar.html'))fetch('/api/me').then(r=>{if(!r.ok)location.href='iniciar.html?return='+encodeURIComponent(location.pathname.split('/').pop())});
 // Profile
 fetch('/api/me').then(r=>r.ok?r.json():null).then(j=>{let u=j?.user;if(!u)return;[['profileName',u.name],['profileUsername',u.username],['profileEmail',u.email]].forEach(([id,v])=>{let e=$('#'+id);if(e)e.value=v||''});if($('#sidebarName'))$('#sidebarName').textContent=u.name;if($('#sidebarUser'))$('#sidebarUser').textContent='@'+u.username;if($('#profileAvatar'))$('#profileAvatar').textContent=(u.name||'U').charAt(0).toUpperCase()}).catch(()=>{});
 $$('.profile-tab').forEach(t=>t.addEventListener('click',()=>{$$('.profile-tab').forEach(x=>x.classList.toggle('active',x===t));$$('.profile-panel').forEach(x=>x.classList.toggle('active',x.dataset.panel===t.dataset.profileTab))}));
 $('#editProfileBtn')?.addEventListener('click',()=>{$$('#profileForm input').forEach(x=>x.disabled=false);$('#profileActions').hidden=false;$('#editProfileBtn').hidden=true});$('#cancelProfile')?.addEventListener('click',()=>location.reload());
 $('#profileForm')?.addEventListener('submit',async e=>{e.preventDefault();let{r,j}=await post('/api/profile',{name:$('#profileName').value,username:$('#profileUsername').value,email:$('#profileEmail').value});if(r.ok)location.reload();else $('#profileMessage').textContent=j.message||'No se pudo guardar.'});
 $('#changePasswordBtn')?.addEventListener('click',()=>{$('#passwordForm').hidden=!$('#passwordForm').hidden});$('#passwordForm')?.addEventListener('submit',async e=>{e.preventDefault();if($('#newPassword').value!==$('#confirmPassword').value){$('#passwordMessage').textContent='Las contraseñas no coinciden.';return}let{r,j}=await post('/api/change-password',{current:$('#currentPassword')?.value,password:$('#newPassword').value});$('#passwordMessage').textContent=j.message||'';if(r.ok)e.target.reset()});
 $$('[data-toggle-password]').forEach(b=>b.addEventListener('click',()=>{let i=$('#'+b.dataset.togglePassword);if(i)i.type=i.type==='password'?'text':'password'}));
 // Recovery: request code, then reset
 let forgotStage=1;$('#forgotForm')?.addEventListener('submit',async e=>{e.preventDefault();let m=$('#forgotMessage');if(forgotStage===1){let{r,j}=await post('/api/forgot/request',{email:$('#forgotEmail').value});m.textContent=j.message||'';if(r.ok){forgotStage=2;$('#forgotCode')?.removeAttribute('hidden');$('#forgotPassword')?.removeAttribute('hidden');$('#forgotConfirm')?.removeAttribute('hidden');$('#forgotForm button[type=submit]').textContent='Cambiar contraseña'}}else{let{r,j}=await post('/api/forgot/reset',{email:$('#forgotEmail').value,code:$('#forgotCode').value,password:$('#forgotPassword').value});m.textContent=j.message||'';if(r.ok)setTimeout(()=>location.href='iniciar.html',700)}});
 // Cart + purchases
 function money(n){return '$'+Number(n).toLocaleString('es-CO')};function renderCart(){let list=$('#cartList');if(!list)return;let sub=0;$$('.cart-item',list).forEach(i=>sub+=(Number(i.dataset.price)||0)*(Number($('[data-qty-value]',i)?.textContent)||1));let tax=Math.round(sub*.19);$('#subtotal')&&( $('#subtotal').textContent=money(sub));$('#tax')&&($('#tax').textContent=money(tax));$('#total')&&($('#total').textContent=money(sub+tax));updateCartCount()};
 $$('.cart-item').forEach(i=>{$$('[data-qty]',i).forEach(b=>b.addEventListener('click',()=>{let q=Math.max(1,(Number($('[data-qty-value]',i).textContent)||1)+Number(b.dataset.qty));$('[data-qty-value]',i).textContent=q;renderCart()}));$('[data-remove]',i)?.addEventListener('click',()=>{i.remove();renderCart()})});renderCart();
 $$('.buy,.cart').forEach(btn=>btn.addEventListener('click',e=>{e.preventDefault();if(!initiated){location.href='iniciar.html?return='+encodeURIComponent(location.pathname.split('/').pop());return}let box=btn.closest('.game-product,.product-container,main')||document,n=box.querySelector('h1')?.textContent?.trim()||'Videojuego',img=box.querySelector('.product-cover img,.game-product img')?.getAttribute('src')||'banner.jpg',pr=parseInt((box.querySelector('.price')?.textContent||'0').replace(/\D/g,''))||0,c=getCart(),x=c.find(a=>a.name===n);x?x.qty++:c.push({name:n,img,price:pr,qty:1});saveCart(c);location.href='carritoiniciada.html'}));
 $('#checkoutBtn')?.addEventListener('click',()=>alert('Compra de demostración realizada. ¡Gracias por usar Pixel Store!'));
});
