const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto');let mailer;try{mailer=require('nodemailer')}catch{}
const PORT=process.env.PORT||3000,oauthStates=new Map(),DATA=path.join(__dirname,'data'),UF=path.join(DATA,'users.json'),RF=path.join(DATA,'reset-codes.json'),sessions=new Map();fs.mkdirSync(DATA,{recursive:true});for(const f of[UF,RF])if(!fs.existsSync(f))fs.writeFileSync(f,'[]');
const read=f=>{try{return JSON.parse(fs.readFileSync(f,'utf8'))}catch{return[]}},write=(f,x)=>fs.writeFileSync(f,JSON.stringify(x,null,2));
const hash=(p,s=crypto.randomBytes(16).toString('hex'))=>new Promise((r,j)=>crypto.scrypt(p,s,64,(e,k)=>e?j(e):r(s+':'+k.toString('hex'))));
const check=(p,h)=>new Promise(r=>{let[s,x]=String(h||'').split(':');if(!s||!x)return r(false);crypto.scrypt(p,s,64,(e,k)=>{try{r(!e&&crypto.timingSafeEqual(Buffer.from(x,'hex'),k))}catch{r(false)}})});
const cookie=(q,n)=>{let m=(q.headers.cookie||'').match(new RegExp('(?:^|; )'+n+'=([^;]*)'));return m&&decodeURIComponent(m[1])};const current=q=>{let s=cookie(q,'pixel_session');return s&&sessions.get(s)};
const json=(r,c,x)=>{r.writeHead(c,{'Content-Type':'application/json','Cache-Control':'no-store'});r.end(JSON.stringify(x))},redir=(r,x)=>{r.writeHead(302,{Location:x});r.end()};const body=q=>new Promise((ok,no)=>{let d='';q.on('data',c=>d+=c);q.on('end',()=>{try{ok(JSON.parse(d||'{}'))}catch(e){no(e)}})});const safe=u=>{let{passwordHash,...a}=u;return a};
async function api(q,r,u){let p=u.pathname,s=current(q);
if(q.method==='GET'&&p==='/api/me'){let a=s&&read(UF).find(x=>x.id===s.id);return a?json(r,200,{ok:true,user:safe(a)}):json(r,401,{ok:false})}
if(q.method==='POST'&&p==='/api/register'){let b=await body(q),email=String(b.email||'').trim().toLowerCase(),username=String(b.username||'').trim().replace(/^@/,''),name=String(b.name||'').trim(),pw=String(b.password||''),us=read(UF);if(!name||!username||!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(email)||pw.length<6)return json(r,400,{ok:false,message:'Completa los datos correctamente.'});if(us.some(x=>x.email.toLowerCase()===email))return json(r,409,{ok:false,message:'Ya existe una cuenta con ese correo.'});if(us.some(x=>x.username.toLowerCase()===username.toLowerCase()))return json(r,409,{ok:false,message:'Ese usuario ya está ocupado.'});let a={id:crypto.randomUUID(),name,username,email,provider:'local',createdAt:new Date().toISOString(),passwordHash:await hash(pw)};us.push(a);write(UF,us);let sid=crypto.randomBytes(32).toString('hex');sessions.set(sid,{id:a.id,expires:Date.now()+6048e5});r.setHeader('Set-Cookie',`pixel_session=${sid}; HttpOnly; Path=/; SameSite=Lax; Max-Age=604800`);return json(r,201,{ok:true})}
if(q.method==='POST'&&p==='/api/login'){let b=await body(q),email=String(b.email||'').trim().toLowerCase(),pw=String(b.password||''),a=read(UF).find(x=>x.email.toLowerCase()===email);if(!a||!a.passwordHash||!(await check(pw,a.passwordHash)))return json(r,401,{ok:false,message:'Correo o contraseña incorrectos.'});let sid=crypto.randomBytes(32).toString('hex');sessions.set(sid,{id:a.id,expires:Date.now()+6048e5});r.setHeader('Set-Cookie',`pixel_session=${sid}; HttpOnly; Path=/; SameSite=Lax; Max-Age=604800`);return json(r,200,{ok:true})}
if(q.method==='POST'&&p==='/api/logout'){let x=cookie(q,'pixel_session');if(x)sessions.delete(x);r.setHeader('Set-Cookie','pixel_session=; HttpOnly; Path=/; Max-Age=0');return json(r,200,{ok:true})}
if(q.method==='POST'&&p==='/api/profile'){let us=read(UF),a=s&&us.find(x=>x.id===s.id);if(!a)return json(r,401,{ok:false});let b=await body(q),email=String(b.email||a.email).trim().toLowerCase(),username=String(b.username||a.username).trim().replace(/^@/,'');if(us.some(x=>x.id!==a.id&&x.email.toLowerCase()===email)||us.some(x=>x.id!==a.id&&x.username.toLowerCase()===username.toLowerCase()))return json(r,409,{ok:false,message:'El correo o usuario ya está en uso.'});Object.assign(a,{name:String(b.name||a.name).trim(),email,username});write(UF,us);return json(r,200,{ok:true,user:safe(a)})}
if(q.method==='POST'&&p==='/api/change-password'){let us=read(UF),a=s&&us.find(x=>x.id===s.id);if(!a||!a.passwordHash)return json(r,400,{ok:false,message:'Esta cuenta no usa contraseña local.'});let b=await body(q);if(!(await check(String(b.current||''),a.passwordHash)))return json(r,400,{ok:false,message:'La contraseña actual no coincide.'});a.passwordHash=await hash(String(b.password||''));write(UF,us);return json(r,200,{ok:true})}
if(q.method==='POST'&&p==='/api/forgot/request'){let b=await body(q),email=String(b.email||'').trim().toLowerCase(),a=read(UF).find(x=>x.email.toLowerCase()===email);if(!a)return json(r,404,{ok:false,message:'No existe una cuenta con ese correo.'});let code=String(crypto.randomInt(0,1e6)).padStart(6,'0'),rs=read(RF).filter(x=>x.email!==email);rs.push({email,code,expires:Date.now()+600000});write(RF,rs);let sent=false;try{if(mailer&&process.env.SMTP_USER&&process.env.SMTP_PASS){let t=mailer.createTransport({host:process.env.SMTP_HOST||'smtp.gmail.com',port:Number(process.env.SMTP_PORT||465),secure:true,auth:{user:process.env.SMTP_USER,pass:process.env.SMTP_PASS}});await t.sendMail({from:process.env.SMTP_FROM||process.env.SMTP_USER,to:email,subject:'Código Pixel Store',text:`Tu código de recuperación es ${code}. Expira en 10 minutos.`});sent=true}}catch(e){console.error(e)}return json(r,200,{ok:true,emailSent:sent,message:sent?'Código enviado al correo.':'Configura Gmail en .env para enviarlo.'})}
if(q.method==='GET'&&(p==='/auth/google'||p==='/auth/discord')){let provider=p.includes('google')?'google':'discord',id=process.env[provider.upper()+'_CLIENT_ID'];if(!id)return redir(r,'/iniciar.html?oauth=not-configured');let state=crypto.randomBytes(18).toString('hex');oauthStates.set(state,{provider,expires:Date.now()+600000});let redirect=process.env[provider.upper()+'_REDIRECT_URI']||`http://localhost:${PORT}/auth/${provider}/callback`;let scope=provider==='google'?'openid email profile':'identify email';let link=provider==='google'?`https://accounts.google.com/o/oauth2/v2/auth?client_id=${encodeURIComponent(id)}&redirect_uri=${encodeURIComponent(redirect)}&response_type=code&scope=${encodeURIComponent(scope)}&state=${state}`:`https://discord.com/oauth2/authorize?client_id=${encodeURIComponent(id)}&redirect_uri=${encodeURIComponent(redirect)}&response_type=code&scope=${encodeURIComponent(scope)}&state=${state}`;return redir(r,link)}
if(q.method==='GET'&&(p==='/auth/google/callback'||p==='/auth/discord/callback')){let provider=p.includes('google')?'google':'discord',state=u.searchParams.get('state'),st=oauthStates.get(state);if(!st||st.provider!==provider||st.expires<Date.now())return redir(r,'/iniciar.html?oauth=invalid');oauthStates.delete(state);let code=u.searchParams.get('code');if(!code)return redir(r,'/iniciar.html');let id=process.env[provider.toUpperCase()+'_CLIENT_ID'],secret=process.env[provider.toUpperCase()+'_CLIENT_SECRET'],redirect=process.env[provider.toUpperCase()+'_REDIRECT_URI']||`http://localhost:${PORT}/auth/${provider}/callback`;try{let token=await fetch(provider==='google'?'https://oauth2.googleapis.com/token':'https://discord.com/api/oauth2/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:id,client_secret:secret,code,redirect_uri:redirect,grant_type:'authorization_code'})}).then(x=>x.json());if(!token.access_token)throw Error('oauth token');let prof=await fetch(provider==='google'?'https://openidconnect.googleapis.com/v1/userinfo':'https://discord.com/api/users/@me',{headers:{Authorization:'Bearer '+token.access_token}}).then(x=>x.json());let email=prof.email;if(!email)throw Error('email');let us=read(UF),a=us.find(x=>x.email.toLowerCase()===email.toLowerCase());if(!a){let base=(prof.name||prof.global_name||prof.username||email.split('@')[0]).replace(/[^a-zA-Z0-9_]/g,'').slice(0,20)||'pixeluser',username=base,n=1;while(us.some(x=>x.username.toLowerCase()===username.toLowerCase()))username=base+(n++);a={id:crypto.randomUUID(),name:prof.name||prof.global_name||prof.username||'Usuario Pixel',username,email,provider,createdAt:new Date().toISOString(),passwordHash:null};a.username=username;us.push(a);write(UF,us)}let sid=crypto.randomBytes(32).toString('hex');sessions.set(sid,{id:a.id,expires:Date.now()+604800000});r.setHeader('Set-Cookie',`pixel_session=${sid}; HttpOnly; Path=/; SameSite=Lax; Max-Age=604800`);return redir(r,'/indexiniciada.html')}catch(e){console.error(e);return redir(r,'/iniciar.html?oauth=error')}}
if(q.method==='POST'&&p==='/api/forgot/reset'){let b=await body(q),email=String(b.email||'').trim().toLowerCase(),code=String(b.code||'').trim(),pw=String(b.password||''),rs=read(RF),z=rs.find(x=>x.email===email&&x.code===code&&x.expires>Date.now()),us=read(UF),a=us.find(x=>x.email.toLowerCase()===email);if(!z||!a)return json(r,400,{ok:false,message:'Código incorrecto o expirado.'});a.passwordHash=await hash(pw);write(UF,us);write(RF,rs.filter(x=>x!==z));return json(r,200,{ok:true})}return false}
const protectedPage=n=>/iniciada\.html$/i.test(n)||['carrito.html','perfil.html','metodosdepago.html'].includes(n.toLowerCase());
http.createServer(async(q,r)=>{let u=new URL(q.url,`http://${q.headers.host||'localhost'}`);if(u.pathname.startsWith('/api/')){try{if(await api(q,r,u)!==false)return}catch(e){console.error(e);return json(r,500,{ok:false,message:'Error interno.'})}}let p=decodeURIComponent(u.pathname);if(p==='/')p='/index.html';let f=path.normalize(path.join(__dirname,p));if(!f.startsWith(__dirname))return r.end('Forbidden');if(protectedPage(path.basename(f))&&!current(q))return redir(r,'/iniciar.html?return='+encodeURIComponent(p));if(path.basename(f)==='iniciar.html'&&current(q))return redir(r,'/indexiniciada.html');fs.stat(f,(e,st)=>{if(e||!st.isFile())return r.end('404');let ext=path.extname(f),types={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'application/javascript; charset=utf-8','.json':'application/json','.jpg':'image/jpeg','.jpeg':'image/jpeg','.png':'image/png','.webp':'image/webp'};r.writeHead(200,{'Content-Type':types[ext]||'application/octet-stream'});fs.createReadStream(f).pipe(r)})}).listen(PORT,()=>console.log(`Pixel Store listo en http://localhost:${PORT}`));
